.TH "/home/djordje/Desktop/orcs/src Directory Reference" 3 "Sat Jan 13 2018" "orcs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/djordje/Desktop/orcs/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolor\&.h\fP"
.br
.RI "\fIDefines all of the ANSI terminal escape codes that modify the color of text\&. \fP"
.in -1c
