.TH "/home/djordje/Desktop/orcs/src/color.h" 3 "Sat Jan 13 2018" "orcs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/djordje/Desktop/orcs/src/color.h \- Defines all of the ANSI terminal escape codes that modify the color of text\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBLACK_TEXT\fP   '\\033[30;1m'"
.br
.ti -1c
.RI "#define \fBRED_TEXT\fP   '\\033[31;1m'"
.br
.ti -1c
.RI "#define \fBGREEN_TEXT\fP   '\\033[32;1m'"
.br
.ti -1c
.RI "#define \fBYELLOW_TEXT\fP   '\\033[33;1m'"
.br
.ti -1c
.RI "#define \fBBLUE_TEXT\fP   '\\033[34;1m'"
.br
.ti -1c
.RI "#define \fBMAGENTA_TEXT\fP   '\\033[35;1m'"
.br
.ti -1c
.RI "#define \fBCYAN_TEXT\fP   '\\033[36;1m'"
.br
.ti -1c
.RI "#define \fBWHITE_TEXT\fP   '\\033[37;1m'"
.br
.ti -1c
.RI "#define \fBBOLD_BLACK_TEXT\fP   '\\033[1m\\033[30m;1m'"
.br
.ti -1c
.RI "#define \fBBOLD_RED_TEXT\fP   '\\033[1m\\033[31m;1m'"
.br
.ti -1c
.RI "#define \fBBOLD_GREEN_TEXT\fP   '\\033[1m\\033[32m;1m'"
.br
.ti -1c
.RI "#define \fBBOLD_YELLOW_TEXT\fP   '\\033[1m\\033[33m;1m'"
.br
.ti -1c
.RI "#define \fBBOLD_BLUE_TEXT\fP   '\\033[1m\\033[34m;1m'"
.br
.ti -1c
.RI "#define \fBBOLD_MAGENTA_TEXT\fP   '\\033[1m\\033[35m;1m'"
.br
.ti -1c
.RI "#define \fBBOLD_CYAN_TEXT\fP   '\\033[1m\\033[36m;1m'"
.br
.ti -1c
.RI "#define \fBBOLD_WHITE_TEXT\fP   '\\033[1m\\033[37m;1m'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_red\fP (void)"
.br
.ti -1c
.RI "void \fBprint_yellow\fP (void)"
.br
.ti -1c
.RI "void \fBprint_blue\fP (void)"
.br
.ti -1c
.RI "void \fBprint_reset\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines all of the ANSI terminal escape codes that modify the color of text\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for orcs from the source code\&.
